language: java
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: "USERNAME-github" # the key of the org you chose at step #3
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
before_install:
  - chmod +x gradlew
script:
  # other script steps might be done before running the actual SonarQube analysis
  - ./gradlew test
  - ./gradlew jacocoTestReport
  - sonar-scanner
